#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
#include <po_hi_messages.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void pinger_deliver 
    (__po_hi_request_t* request);

/*  Periodic task : Pinger*/

void* pinger_job ();

void ping_me_deliver 
    (__po_hi_request_t* request);

/*  Sporadic task : Ping_Me*/

void* ping_me_job ();

void __po_hi_main_deliver 
    (__po_hi_msg_t* message);

#endif
