#include <deployment.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_entity_t __po_hi_port_global_to_entity[__PO_HI_NB_PORTS] = {node_a_pinger_k_entity,node_a_ping_me_k_entity};
__po_hi_local_port_t __po_hi_port_global_to_local[__PO_HI_NB_PORTS] = {pinger_local_data_source,ping_me_local_data_sink};
__po_hi_node_t entity_table[__PO_HI_NB_ENTITIES] = {node_a_k,node_a_k};

