#include <activity.h>
#include <po_hi_common.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_task.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

/************************/
/* __PO_HI_MAIN_NAME   */ 
/***********************/

__PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME ()
{

  __po_hi_initialize ();
  __po_hi_create_periodic_task (node_a_pinger_k, __po_hi_milliseconds (1000), 2, 0, pinger_job);
  __po_hi_create_sporadic_task (node_a_ping_me_k, __po_hi_milliseconds (10), 1, 0, ping_me_job);
  __po_hi_wait_initialization ();
  __po_hi_wait_for_tasks ();
  return (__PO_HI_MAIN_RETURN);
}


