#include <po_hi_protocols.h>
#include <deployment.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_inetport_t node_port[__PO_HI_NB_NODES] = {};
__po_hi_inetaddr_t node_addr[__PO_HI_NB_NODES] = {};
__po_hi_node_t mynode = node_a_k;

