#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_do_ping_spg 
    (simple_type* data_source);

/******************/
/* do_ping_spg   */ 
/*****************/

void do_ping_spg 
    (simple_type* data_source)
{

  user_do_ping_spg (data_source);
}

void user_ping_spg 
    (simple_type data_sink);

/***************/
/* ping_spg   */ 
/**************/

void ping_spg 
    (simple_type data_sink)
{

  user_ping_spg (data_sink);
}


